[project]
name = "pass-manager"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.22.1",
    "cryptography>=46.0.3",
    "loguru>=0.7.3",
    "pydantic>=2.12.5",
    "pyinstaller>=6.17.0",
    "sqlalchemy>=2.0.45",
]
